### ISSUE TITLE
Failed to receive inbound message

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/fusionpbx-webtexting#12]
This incoming SMS failed to be forwarded by the Messaging API to the registered callbackUrl. I don't see anything that the Messaging API did wrong and the response is 500, which leads me to believe that this is an issue internal issue with webtexting.

Here's the content of the message:

> 8/19/2023 8:38 PM Hey ..., your order from ... is being delivered at 9:00 PM. You can track the status at https://drd.sh/...

Here's what the Messaging API responded to the incoming message with:

> Failed to forward message to FinnsNumberEndingIn9327 at https://acceleratenetworks.sip.callpipe.com/app/webtexting/inbound-hook.php?provider=accelerate-networks 500 {"error":"failed send, please retry later"}

Where the final bit of JSON is what the Messaging API received from the callbackUrl.

I can provided an exact copy of the forwarded JSON if you'd like, but it contains PII so I'd rather not.

**Comment by danry25** [comment]
This issue appears to be caused by TLS certificates expiring for *.sip.callpipe.com, and we need to sort our Prometheus alerting to monitor for this. Not really a Web Texting issue, rather a system operations issue.
