### ISSUE TITLE
Push Notifications not working in Chrome on Production

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#24]
Chrome doesn't show the push notification prompt due to this error in production web texting.

`Uncaught (in promise) DOMException: Push subscriptions that don't enable userVisibleOnly are not supported.`

![image](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/1683673/796ba8fe-afd0-42a6-9135-f5c99aa2d0a5)

**Comment by thefinn93** [comment]
whoops! stupid chrome requirement, fix here is very easy. add `userVisibleOnly: true` to https://github.com/AccelerateNetworks/fusionpbx-webtexting/blob/main/webtexting.js#L48 like this and it should work. No frontend rebuild required.

```js
subscription = await registration.pushManager.subscribe({ applicationServerKey: convertedVapidKey, userVisibleOnly: true });

**Comment by danry25** [comment]
Hmm, I tested this in Chromium (Version 116.0.5845.180 (Official Build) built on Debian 12.1, running on Debian 12.2 (64-bit)) but it doesn't seem to resolve the DOMException, getting the same userVisibleOnly error.

![image](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/1683673/df6e478f-ecc2-4744-88a5-73c4cbb9aff0)

**Comment by dunkeltron** [comment]
There's another place you need to add the userVisibleOnly:true option on line 105 of webtexting.js
Before:
const state = await registration.pushManager.permissionState();
After:
const state = await registration.pushManager.permissionState({userVisibleOnly:true});
