### ISSUE TITLE
Push Notifications don't notify

### ISSUE THREAD

**Issue by dunkeltron** [AccelerateNetworks/fusionpbx-webtexting#25]
Seems like I need to do more work understanding how notifications make it from notifications.php to the user

**Comment by uncheckederror** [comment]
I've been doing some research into getting push notifications to work in Chrome. I believe you should read this doc:

[https://web.dev/articles/push-notifications-overview](https://web.dev/articles/push-notifications-overview)

Looking at the composer.lock file in this project it would appear that the [web-push-php library](https://github.com/web-push-libs/web-push-php) is being used to send push events to the client side browser.

The first step in the notifications doc from Google linked above is to prompt the user to allow or disallow Web Texting to send them notifications. So we need to trigger the browser to execute this prompt action, which our code doesn't appear to be doing right now. Then we can register our service worker with the browser and push events to it, and then the user, from our php code.

**Comment by dunkeltron** [comment]
Turns out push notifications do notify it's just that my test bench had notifications turned off on three separate levels

**Comment by uncheckederror** [comment]
Can we close this issue then?

**Comment by dunkeltron** [comment]
yeah i thought i hit close with comment
