### ISSUE TITLE
notifications icon in webtexting ui icon issues

### ISSUE THREAD

**Issue by dunkeltron** [AccelerateNetworks/fusionpbx-webtexting#33]
sometimes the fusionpbx webtexting ui icons are double rendered. 
the group contact edit icon is double rendered sometimes.
the notifications icon is sometimes misrepresenting the truth ( for example legacy per contact notifications can be displayed as no notifications)

**Comment by dunkeltron** [comment]
So it turns out that the group contact edit button was not double rendering one link it was using the same icon for contact edit and change group name. which is also a problem.

**Comment by uncheckederror** [comment]
Related to #43

**Comment by dunkeltron** [comment]
this is resolved
