### ISSUE TITLE
Improve formatting of Conversation List

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#4]
The current conversation list has no visual boundary between conversations. This is not good at making an effective use of space.

It would also be good to:

- [x] - Color code conversations (color coded inbound and outbound messages in conversations)
- [x] - Lean on the FusionPBX contacts (and create contacts from CNAM data) to lookup contact names
- [x] #60
- [x] - Allow other users to access the messages sent to a given number
- [x] - Show the number you are sending texts as
- [ ] #54
- [ ] #55
- [ ] - Enable templating of outbound messages #36 
- [ ] #56
- [ ] #61
- [ ] #57
- [x] - Pick which outbound number you are sending as for extensions with multiple numbers assigned
- [x] - Add a left side bar with a list of conversations
- [ ] #58
- [ ] #59

**Comment by dunkeltron** [comment]
Triaged and moved the non closed points to separate issues
