### ISSUE TITLE
Info Button in Conversations header leads to Accelerate Networks main page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#42]
I find myself pressing the info button in the Conversations header by accident (when I mean to press the bell icon to subscribe to push notifications) often, and it leads me to https://acceleratenetworks.com/support/ which isn't texting specific.

Do we want to route this button to a texting specific support page, and give it some space from other clickable elements so its not mistakenly clicked?

**Comment by uncheckederror** [comment]
@danry25 we don't have a texting specific support page on the website. Happy to add one, but I'd need you to put together some content.

**Comment by uncheckederror** [comment]
To make the bell button and the info button larger we can add btn and btn-large to the list of CSS classes applied to each button. Using a large size will make it easier for users on mobile devices to tap the correct button. 

For the parent div we need to add 3 CSS classes: d-flex justify-content-start align-items-end where the threadlist-header class is already present. 

We can improve this further by wrapping the text Conversation in a h6 tag and then a div, then we'll need to wrap the two icons in a div. Finally we can update the flex class of the parent div from justify-content-start to justify-content-between.

![image](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/11726956/2c43eb2e-9bea-4081-a85e-d9a1cfa0c661)

**Comment by dunkeltron** [comment]
notifications bell is spaced out now

**Comment by danry25** [comment]
**Enabling Notifications (Desktop & Android)**
Tap the Bell Icon and choose Allow Notifications when prompted by your web browser.
[simplescreenrecorder-2024-03-15_15.44.54.webm](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/1683673/16056c7c-e950-4f6a-943d-fd3b0ccbf473)

**Comment by dunkeltron** [comment]
I removed the info button and fixed the bell so I'm closing this
