### ISSUE TITLE
Pencil Icon to edit Contact not consistently appearing

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#43]
We have gotten reports that the pencil icon is not consistently appearing in Web Texting (see Ticket #422187 for a video of this issue).

**Comment by dunkeltron** [comment]
this might've been fixed with the most recent push

**Comment by danry25** [comment]
This issue persists :c

**Comment by dunkeltron** [comment]
Should be implemented feel free to test and close
