### ISSUE TITLE
iOS notifications blocked by fusionpbx architecture.

### ISSUE THREAD

**Issue by dunkeltron** [AccelerateNetworks/fusionpbx-webtexting#45]
FusionPBX delivers a default template /themes/default/template.php.
in [header.php](https://github.com/AccelerateNetworks/fusionpbx/blob/331628ce1579b33fecd12f535ea7c08dc548331a/resources/header.php#L54) and [footer.php](https://github.com/AccelerateNetworks/fusionpbx/blob/331628ce1579b33fecd12f535ea7c08dc548331a/resources/footer.php#L61) fpbx checks for a user setting at '/'.$_SESSION['domain']['template']['name'].'/template.php'
However in the default settings page this setting is dropdown with two choice: default or customerthemes.

I tested this in debugging and If you select customerthemes  '/'.$_SESSION['domain']['template']['name'].'/template.php' evaluates to themes/customerthemes/template.php.

The workaround for this is to dump our template.php into customerthemes but this is in conflict with mark's direction for customer theming stuff to go into a folder named AccelerateNetworks (for example this is where the AccelerateNetworks logo.png exists)

if default setting is changed to text this needs to be updated in the header.php and footer.php files. Another options is to potentially allow us to add our name to the list of options in the domain->template->name dropdown in the default settings page.

@danry25 if you could bring this up with Mark on your next call that'd allow us to move forward with iOS notifications / adding to home screen as a web app instead of bookmark

**Comment by danry25** [comment]
To recap our conversation, we need /var/www/fusionpbx/themes/default/template.php to contain this:
```
{*//manifest file for installibility *}
	<link rel='manifest'  href='{$project_path}/{$webapp_path}'>
```
The webapp_path needs to be set to app/webtexting/manifest.php for this to be installable as a Web App with push notifications on iOS,

Then a manifest needs to be created in the relevant folder, [like this one](https://github.com/AccelerateNetworks/fusionpbx-webtexting/blob/sidebyside/manifest.php).

**Comment by dunkeltron** [comment]
I believe we have a workaround up for our sfo and sfo2 instances of fpbx. Can we close this?
