### ISSUE TITLE
Handle user assigned to multiple Web Texting enabled extensions

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#47]
Web Texting can be enabled on multiple extensions that a user is assigned to, and there is currently no way to swap between these instances of Web Texting.

Prior to the change to a single page view of the threads and converations, there was an intermediate page before threadlist that showed all Web Texting instances assigned to the user.

If we could add this functionality back in, it would be appreciated by our end users (NCL specifically).

**Comment by dunkeltron** [comment]
Believe this is implemented. Please verify
