### ISSUE TITLE
Threadlist does not show threads started from FusionPBX

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#5]
Starting a conversation with 12065551234 doesn't cause the Threadlist.php page to show that a new conversation has been started, despite sms.callpipe.com accepting the text and the texting thread being accessible if you modify the URL to https://domain/app/webtexting/thread.php?extension_uuid=433509d9-f948-400f-849c-667f9d4c327c&number=12065551234&action=Ok&key_uuid=

**Comment by thefinn93** [comment]
what does this mean? You started a new thread but didn't send anything and you're expecting that to create an entry in the thread list?

**Comment by danry25** [comment]
The carrier's billing logs show this message as delivered (which we have a separate ticket open about), and the message shows up for me when I go to the thread via URL.

![signal-2023-08-06-12-16-07-599](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/1683673/2550e11f-8738-43e7-b69c-927cc5185cde)
