### ISSUE TITLE
Start a new conversation button does not move correctly to match window height

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#51]
The + button to start a new conversation is not visible in Safari on an iPhone SE 2022 nor is it visible when your desktop browser's window is too small.

[BootstrapIssues-2024-03-15_16.05.58.webm](https://github.com/AccelerateNetworks/fusionpbx-webtexting/assets/1683673/a5b3be98-a1d1-47a5-aab0-f2b2a4297be4)

**Comment by dunkeltron** [comment]
#66 This might be part of the various css issues

**Comment by uncheckederror** [comment]
This appears to be fixed on my iPhone SE.
