### ISSUE TITLE
[BUG] Miscellaneous CSS issues

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/fusionpbx-webtexting#66]
![WebTextingCSSIssues](https://github.com/user-attachments/assets/2deab118-3fa4-4e88-a348-98cb5caeb54c)

There are a few issues with the CSS in WebTexting:

- [x] The items in the Conversations list are offset on the left edge by a couple of pixels, when compared to the blue header above them.
- [x] Inside of a item on the Conversations list, the content preview of the message extends all the way until the edge of the item without any padding or wrapping.
- [x] #70

**Comment by dunkeltron** [comment]
I've got these fixes scheduled for the next deployment.
<img width="1124" alt="Screenshot 2024-11-21 at 5 47 40 PM" src="https://github.com/user-attachments/assets/ca54dd4d-4c61-43f7-bbeb-38c4086e4962">
