### ISSUE TITLE
SMSes over 160 characters are dropped silently

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#9]
Sending SMSes that are more than 160 characters ([if GSM-7 formatted](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding)) or 70 characters if non-GSM-7 characters are included seems to fail silently in Web Texting and in OrgSMS.

My understanding from our June 19th 2023 conversation was these messages would be upgraded by the client application to MMSes.

It would be great if we could display a character counter to the end user, advising that they have 160 characters to work with, or 1600 once they roll past the 160 character limit.

These strings silently fail to send for example:
`🎉🔥✅Hello ☃️, this is a test string that should reproduce a fun bug! Wohoo!🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥`

`A single SMS message technically supports up to 160 characters, or up to 70 if the message contains one or more Unicode characters (such as emoji or Chinese char`

Meanwhile these send without issue:
`🎉🔥✅Hello ☃️, this is a test string that should reproduce a fun bug! Wohoo!🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🎉🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅🔥✅`

`A single SMS message technically supports up to 160 characters, or up to 70 if the message contains one or more Unicode characters (such as emoji or Chinese cha`

**Comment by uncheckederror** [comment]
Per Hannah we are getting this feedback from users:

> Angela Figgins at A Sign of Hope would appreciate it if the UI actually cut off at 160 characters and wouldn’t let her type more than that or have a character count visible

**Comment by dunkeltron** [comment]
app no longer allows more than 160 characters in the SendBox component
